"""Negative controls: what the toolkit refuses to claim (source notebook, Section 6).

A rigour tool is defined as much by what it declines to output as by what it
computes. These tests port Section 6's three demonstrations verbatim: on data
where the ground truth is known by construction, three quantities that a more
"ambitious" toolkit might advertise are provably **not identifiable** from the
data available. Each is a feature this toolkit deliberately does not ship, and
these tests are the proof.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score


class TestMARvsMNARUnidentifiable:
    """Section 6.1. Two datasets with the SAME observed distribution but DIFFERENT
    full-data truth -- one generated by an MNAR mechanism, one by MAR. Because the
    missing values are, by definition, unobserved, every statistic computable on
    the observed data returns the same value. The mechanism cannot be recovered;
    this is a theorem, not a limitation of any particular algorithm [17,20]. No
    "MNAR likelihood" score is shipped by cmvt.integrity.
    """

    def test_observed_marginals_are_indistinguishable_while_truth_differs(self):
        rng = np.random.default_rng(11)
        N = 20000

        # Scenario A (MNAR): full data uniform on {0,1,2,3}; P(missing|X=x) rises with x.
        X_full = rng.integers(0, 4, N)
        obs_A = ~(rng.random(N) < np.array([0.1, 0.3, 0.5, 0.7])[X_full])
        observed_X_A = X_full[obs_A]
        target = np.bincount(observed_X_A, minlength=4) / obs_A.sum()

        # Scenario B (MAR): DIFFERENT full data (right-skewed) + MAR keep-prob
        # reproducing A's observed marginal.
        X_full_B = rng.choice(4, size=N, p=[0.15, 0.2, 0.25, 0.4])
        full_B = np.bincount(X_full_B, minlength=4) / N
        keep = target / (full_B + 1e-12)
        keep /= keep.max()
        obs_B = rng.random(N) < keep[X_full_B]
        observed_X_B = X_full_B[obs_B]

        oa = np.bincount(observed_X_A, minlength=4) / obs_A.sum()
        ob = np.bincount(observed_X_B, minlength=4) / obs_B.sum()
        full_truth_A = np.bincount(X_full, minlength=4) / N
        full_truth_B = np.bincount(X_full_B, minlength=4) / N

        # The claim: observed data is (almost) identical between the two scenarios...
        assert np.abs(oa - ob).max() < 0.02
        # ...while the full-data truth is NOT identical -- the mechanism genuinely
        # differs, but nothing in the observed data can tell you that.
        assert np.abs(full_truth_A - full_truth_B).max() > 0.05
        # => identical observed data, different truth: mechanism UNIDENTIFIABLE.


class TestCompositeQualityScoreIsWeightDependent:
    """Section 6.2. Combining sub-metrics into one "dataset quality score" hides the
    weights inside a single number. Three datasets, each strongest on a different
    dimension, are scored under four equally defensible weightings; the top-ranked
    dataset changes with the weights. The score encodes the author's priorities,
    not a property of the data -- so cmvt reports sub-metrics and refuses to
    collapse them into a rank [21].
    """

    def test_top_ranked_dataset_swings_with_weighting(self):
        datasets = pd.DataFrame({
            "dataset": ["Cohort_A", "Cohort_B", "Cohort_C"],
            "completeness": [0.95, 0.55, 0.65],
            "balance": [0.50, 0.95, 0.60],
            "size": [0.60, 0.55, 0.95],
            "shift_free": [0.70, 0.75, 0.72],
        }).set_index("dataset")
        dims = ["completeness", "balance", "size", "shift_free"]
        weightings = {
            "equal": [.25, .25, .25, .25],
            "clinician": [.55, .25, .10, .10],
            "trialist": [.10, .55, .25, .10],
            "ml_engineer": [.10, .15, .55, .20],
        }
        ranks = pd.DataFrame({
            n: pd.Series((datasets[dims].values * np.array(w)).sum(1), index=datasets.index)
                .rank(ascending=False).astype(int)
            for n, w in weightings.items()
        })
        winners = ranks.apply(lambda c: c.idxmin())
        # At least 3 of the 4 equally-defensible weightings crown a different #1 dataset.
        assert winners.nunique() >= 3


class TestSemanticLeakageIsUndecidableFromValues:
    """Section 6.3. Two columns with IDENTICAL statistical relationships to the
    outcome -- one a pre-outcome biomarker (legitimate), one computed from the
    label (a leak). Every value-based statistic (correlation, AUROC, mean
    difference) is the same; only knowing *how each column was computed*
    (provenance) resolves it. cmvt.integrity.leakage_scan therefore ships only the
    decidable checks (Section 4.2) and refuses a values-only leakage score.
    """

    def test_legitimate_and_leaked_columns_are_statistically_indistinguishable(self):
        rng = np.random.default_rng(5)
        n = 8000
        y = rng.integers(0, 2, n)
        legit = 0.9 * y + rng.normal(0, 1, n)  # pre-outcome biomarker (legitimate)
        leak = 0.9 * y + rng.normal(0, 1, n)   # outcome-derived, identical construction (leak)

        def col_stats(c):
            return dict(
                corr_with_y=np.corrcoef(c, y)[0, 1],
                auroc=roc_auc_score(y, c),
                mean_diff=c[y == 1].mean() - c[y == 0].mean(),
            )

        legit_stats = col_stats(legit)
        leak_stats = col_stats(leak)
        max_abs_diff = max(abs(legit_stats[k] - leak_stats[k]) for k in legit_stats)
        # Statistically indistinguishable despite one being an outcome-derived leak.
        assert max_abs_diff < 0.05
