"""Section 7 — Automated validation report.

The toolkit's endpoint is a single reproducible report that assembles every
computed result into one document mapped to the applicable reporting standard. It
is generated by a real function running on the results above -- not a template with
blanks. The report states, in one place, what was measured, and it names explicitly
what it refuses to claim (the negative controls of Section 6 / see
:mod:`cmvt` docs). This is the artifact a team would attach to a validation
submission.
"""

from __future__ import annotations

import pandas as pd

__all__ = ["build_validation_report"]


def build_validation_report(plan: pd.DataFrame, cohorts: dict, shared_features, leakage_df: pd.DataFrame,
                             ablation_df: pd.DataFrame, dca_df: pd.DataFrame, fairness_disp: dict,
                             psi_mean: float) -> str:
    """Assemble a single markdown validation report from computed results. No hidden state.

    Every section is generated from a value that was actually computed by the
    caller (the ``validation_plan``, ``leakage_scan``, ``ablation_runner``,
    ``decision_curve``, and ``fairness_panel`` outputs) -- there is no templated
    placeholder text. Section 7 ("Deliberately omitted") is fixed prose naming the
    three negative controls (Section 6 of the source notebook /
    ``tests/test_negative_controls.py``) so every report states, in one place, what
    the toolkit refuses to claim.

    Returns
    -------
    str
        The report as GitHub-flavoured markdown.
    """
    L: list[str] = []
    A = L.append
    A("# Automated Validation Report\n")
    A("_Generated by clinical-model-validation-toolkit (cmvt) on bundled synthetic cohorts. "
      "All numbers are computed live; none is a clinical performance claim._\n")
    A("## 1. Transportability (validation engine)\n")
    A("| cohort | naive AUROC | fair AUROC | true-shift gap | information-loss confound |")
    A("|---|---|---|---|---|")
    for r in plan.index:
        A(f"| {r} | {plan.loc[r, 'naive_auroc']:.3f} | {plan.loc[r, 'fair_auroc']:.3f} | "
          f"{plan.loc[r, 'fair_gap_true_shift']:+.3f} | {plan.loc[r, 'information_loss_confound']:+.3f} |")
    A(f"\n**Interpretation.** Naive external transfer loses {plan.loc['external', 'naive_gap']:.3f} AUROC, "
      f"of which {plan.loc['external', 'fair_gap_true_shift']:.3f} is true distribution shift and "
      f"{plan.loc['external', 'information_loss_confound']:.3f} is information loss from unrecorded "
      f"features. Applicable standard: **TRIPOD+AI** (external validation).\n")
    band = "major" if psi_mean > 0.25 else "moderate" if psi_mean > 0.1 else "negligible"
    A(f"## 2. Distribution shift\n\n- Mean PSI internal->external: {psi_mean:.3f} ({band} shift).\n")
    A("## 3. Data-integrity (decidable leakage checks)\n")
    for _, row in leakage_df.iterrows():
        A(f"- {row['check']}: {'PASS' if row['passed'] else 'FAIL'} — {row['detail']}")
    A("\n## 4. Component ablation\n")
    for _, row in ablation_df[ablation_df.config != "full"].iterrows():
        A(f"- remove {row['removed']}: deltaAUROC {row['delta']:+.3f} (verified-zeroing: {row['verified']})")
    A(f"\n## 5. Clinical utility\n\n- Net benefit at threshold 0.20: {dca_df.iloc[19]['nb_model']:.3f} "
      f"(treat-all {dca_df.iloc[19]['nb_treat_all']:.3f}, treat-none 0.000).\n")
    A(f"## 6. Subgroup disparities (reported, not diagnosed)\n\n- max-min AUROC disparity: "
      f"{fairness_disp['auroc']:.3f}; ECE disparity {fairness_disp['ece']:.3f}. Cause not inferred.\n")
    A("## 7. Deliberately omitted\n\n- No MNAR likelihood (unidentifiable, NC1). No composite "
      "quality score (rank-unstable, NC2). No values-only leakage score (undecidable, NC3). "
      "No causal attribution of disparity.\n")
    A("## 8. Reporting-standard note\n\nMaps to **TRIPOD+AI** for validation & calibration. Protocol -> "
      "**SPIRIT-AI**; trial -> **CONSORT-AI**; risk-of-bias -> **PROBAST-AI**; diagnostic accuracy -> "
      "**STARD-AI**; decision-analytic -> **CHEERS-AI**.")
    return "\n".join(L)
